modLoader="javafml"
loaderVersion="[42,)"
license="LGPL v2.1"
[[mods]]
modId="l2archery"
version="${file.jarVersion}" #mandatory
displayName="L2 Archery" #mandatory
logoFile="l2archery.png" #optional
authors="lcy0x1 and LightLand team" #optional
description='''
Useful specialized bows and arrows that have unique effects.
Combine them for better combat experience
'''
[[dependencies.l2archery]]
    modId="forge"
    mandatory=true
    versionRange="[4.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.l2archery]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.1,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.l2archery]]
    modId="l2library"
    mandatory=true
    versionRange="[1.8.2,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.l2archery]]
    modId="l2complements"
    mandatory=true
    versionRange="[0.2.1,)"
    ordering="AFTER"
    side="BOTH"